[project]
name = "playwright-python-automation-framework"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = []

[dependency-groups]
dev = [
    "playwright>=1.62.0",
    "pytest>=9.1.1",
    "pytest-playwright>=0.8.0",
    "ruff>=0.16.2",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "automation_framework"
module-root = "src"

[tool.pytest.ini_options]
base_url = "https://practicesoftwaretesting.com"
